<x-index>
</x-index>

<table>
    <thead>
      <tr>
        <th colspan="8">User 테이블</th>
      </tr>
    </thead>
    <tbody>
      <tr id="structure">
        <td>Field</td>
        <td>Type</td>
        <td>Length</td>
        <td>Unsigned</td>
        <td>AllowNull</td>
        <td>Key</td>
        <td>Extra</td>
        <td>Encoding</td>
      </tr>
      <tr>
        <td>id</td>
        <td>BIGINT</td>
        <td></td>
        <td></td>
        <td></td>
        <td>PRI</td>
        <td>auto_increment</td>
        <td></td>
      </tr>
      <tr>
        <td>username</td>
        <td>VARCHAR</td>
        <td>255</td>
        <td>O</td>
        <td></td>
        <td>UNI</td>
        <td></td>
        <td>UTF-8 Unicode(utf8mb4)</td>
      </tr>
      <tr>
        <td>name</td>
        <td>VARCHAR</td>
        <td>255</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>UTF-8 Unicode(utf8mb4)</td>
      </tr>
      <tr>
        <td>email</td>
        <td>VARCHAR</td>
        <td>255</td>
        <td></td>
        <td></td>
        <td>UNI</td>
        <td></td>
        <td>UTF-8 Unicode(utf8mb4)</td>
      </tr>
      <tr>
        <td>password</td>
        <td>VARCHAR</td>
        <td>255</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>UTF-8 Unicode(utf8mb4)</td>
      </tr>
      <tr>
        <td>remember_token</td>
        <td>VARCHAR</td>
        <td>100</td>
        <td></td>
        <td>O</td>
        <td></td>
        <td></td>
        <td>UTF-8 Unicode(utf8mb4)</td>
      </tr>
      <tr>
        <td>created_at</td>
        <td>TIMESTAMP</td>
        <td></td>
        <td></td>
        <td>O</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>updated_at</td>
        <td>TIMESTAMP</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    </tbody>
</table>
